on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Github asction'
        run: pwd  

      - name: 'Testing printing'
        run: echo ahmad     
